### ISSUE TITLE
OpenWeather

### ISSUE THREAD

**Issue by Donkey-Doug** [davidtakac/prognoza#30] opened 2022-12-21 22:36 UTC
Perhaps add support for openweather. The MET Norway data is not accurate at all in the netherlands.

**Comment by davidtakac** [comment] 2022-12-22 07:18
Hi, thank you for the suggestion. This is a duplicate of #12, all weather data source discussion is done there. Multiple weather data sources are a planned feature, but OpenWeatherMap is not since it's not free software.

**Closed as not planned** 2022-12-22 07:19 UTC
Labels: duplicate, wontfix
