### ISSUE TITLE
[Feature Request] Daily low and high temperatures for coming days when collapsed

### ISSUE THREAD

**Issue by basilbasilikum** [davidtakac/prognoza#46] opened 2023-02-08 20:23 UTC
Currently the low and high temperatures for coming days can only be seen when the day is expanded. It's not convenient when we just want to know at a glance the temperatures for the coming days.

**Comment by davidtakac** [comment] 2023-02-14 17:32
This is a duplicate of #35 . I'll see what I can do, it seems like people would prefer this.

**Closed as completed** 2023-02-14 17:32 UTC
Labels: duplicate
